### ISSUE TITLE
mamba-ssm , cannot be compiled on windows

### ISSUE THREAD

**Issue by patientx** [Zyphra/Zonos#27]
Tried various solutions suggested on the interwebs, there are precompiled packages but they are all for linux. Please share windows packages or warn people it is not likely they can make it compile ...

**Comment by sekstini** [comment]
Hey, thanks for the comment. I updated the README to clarify system requirements. We are not likely to support Windows in this repository due to the mamba-ssm dependency, but intend to release a separate repository that has broader hardware support in the coming days.

**Comment by AznamirWoW** [comment]
for those who wonder how,
download mamba_ssm .gzip from pypi.org manually, unzip, copy mamba_ssm folder into Zonos cloned folder.

Other must have requirements:
Python 3.11.9, torch 2.5.1+cu121 (or cu124), triton 3.2 ( https://github.com/woct0rdho/triton-windows/releases/tag/v3.2.0-windows.post9 ), flash attention ( https://huggingface.co/lldacing/flash-attention-windows-wheel/blob/main/flash_attn-2.7.0.post2%2Bcu124torch2.5.1cxx11abiFALSE-cp311-cp311-win_amd64.whl )

**Comment by Mikerhinos** [comment]
> for those who wonder how, download mamba_ssm .gzip from pypi.org manually, unzip, copy mamba_ssm folder into Zonos cloned folder.
> 

Which gzip ? I get a tar.gz source file on pypi.org.
I tried to extract the folder in root Zonos, in the site-packages and in /zonos folder but I still can't compile with "uv sync --extra compile" :/

**Comment by AznamirWoW** [comment]
> > for those who wonder how, download mamba_ssm .gzip from pypi.org manually, unzip, copy mamba_ssm folder into Zonos cloned folder.
> 
> Which gzip ? I get a tar.gz source file on pypi.org. I tried to extract the folder in root Zonos, in the site-packages and in /zonos folder but I still can't compile with "uv sync --extra compile" :/

mamba_ssm-2.2.4.tar.gz

this folder
![Image](https://github.com/user-attachments/assets/50fa0a33-efde-44b7-835d-9393036b2fcf)

to here
![Image](https://github.com/user-attachments/assets/b700f61b-5e15-41c5-b874-0b4f65ef5ff6)

**Comment by Mikerhinos** [comment]
> > > for those who wonder how, download mamba_ssm .gzip from pypi.org manually, unzip, copy mamba_ssm folder into Zonos cloned folder.
> > 
> > 
> > Which gzip ? I get a tar.gz source file on pypi.org. I tried to extract the folder in root Zonos, in the site-packages and in /zonos folder but I still can't compile with "uv sync --extra compile" :/
> 
> mamba_ssm-2.2.4.tar.gz
> 
> this folder ![Image](https://github.com/user-attachments/assets/50fa0a33-efde-44b7-835d-9393036b2fcf)
> 
> to here ![Image](https://github.com/user-attachments/assets/b700f61b-5e15-41c5-b874-0b4f65ef5ff6)
> 
> You dont need to compile anything.
> 
> Just clone Zonos, make virtual environment, activate, then run `pip install -e .` then install proper cuda torch using pip install.

Oh ok I was trying the uv method, which fails.
Will update trying the pip method when I'll be home, thanks :)

**Comment by brknsoul** [comment]
Got the gradio interface to launch, the model got downloaded, but when I try to generate i get;

`RuntimeError: espeak not installed on your system`

espeak-ng is installed, in PATH.
tried symlinking espeak.exe to espeak-ng.exe, tried copying the dll to zonos folder, tried `pip install espeakng`, no dice

**Comment by sdbds** [comment]
![Image](https://github.com/user-attachments/assets/3bae4361-d12d-4bc8-a565-672eb162cdce)
https://github.com/sdbds/Zonos-for-windows

**Comment by t-mat** [comment]
@brknsoul, if phonemizer reports your error, you probably should set environment variable
`PHONEMIZER_ESPEAK_LIBRARY`.  See also: https://github.com/bootphon/phonemizer/issues/44#issuecomment-1008449718

**Comment by brknsoul** [comment]
> [@brknsoul](https://github.com/brknsoul), if phonemizer reports your error, you probably should set environment variable `PHONEMIZER_ESPEAK_LIBRARY`. See also: [bootphon/phonemizer#44 (comment)](https://github.com/bootphon/phonemizer/issues/44#issuecomment-1008449718)

Already tried the env vars.

**Comment by AznamirWoW** [comment]
> Got the gradio interface to launch, the model got downloaded, but when I try to generate i get;
> 
> `RuntimeError: espeak not installed on your system`
> 
> espeak-ng is installed, in PATH. tried symlinking espeak.exe to espeak-ng.exe, tried copying the dll to zonos folder, tried `pip install espeakng`, no dice

add this

![Image](https://github.com/user-attachments/assets/0c692872-0fd2-4ec3-adeb-c4b589f0371f)
